### ISSUE TITLE
Status check not working on one site

### ISSUE THREAD

**Issue by iburrows** [CastawayLabs/cachet-monitor#124]
Hi, the monitor is working well for all of the endpoints except for one. Even though the endpoint returns 200.
It is for a Hashicorp Vault instance and returns:
```json
{
  "initialized": true,
  "sealed": false,
  "standby": false,
  "performance_standby": false,
  "replication_performance_mode": "disabled",
  "replication_dr_mode": "disabled",
  "server_time_utc": 1588661588,
  "version": "1.4.0",
  "cluster_name": "vault-cluster",
  "cluster_id": "123456qwqw-sdfs"
}
```
The monitor always shows that part of the requests are filling the threshold.
This is my config file:
```yaml
api:
  # cachet url
  url: https://status.com/api/v1
  # cachet api token
  token: TOKEN
  insecure: false
date_format: 02/01/2006 15:04:05 MST
monitors:
  - name: Vault
    target: https://vault.instance/v1/sys/health
    strict: true
    method: GET
    component_id: 6
    interval: 10
    timeout: 1
    threshold: 80
    expected_status_code: 200
```
